### ISSUE TITLE
how to configure in docker-compose

### ISSUE THREAD

**Issue by cavazquez** [prometheus-community/bind_exporter#100]
bind_exporter:
      image: "prometheuscommunity/bind-exporter:v0.4.0"       
      container_name: "bind_exporter"
      restart: "unless-stopped"
      command: "-bind.stats-url http://fqdn-example:8053"

the container restart always.   if change to  "--bind.stats-url"  the bind_up 0

can anybody help me?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by bondif** [comment]
I had the same issue, any solution ?

**Comment by phpipam** [comment]
```yml
command: --bind.stats-url=http://<ip>:8053
```
