### ISSUE TITLE
How to get metrics from docker 

### ISSUE THREAD

**Issue by offlinejke** [prometheus-community/bind_exporter#104]
My docker-compose.yml.  I've got error in prom `read: connection reset by peer`.
`  bind:
    image: prometheuscommunity/bind-exporter:v0.3.0
    container_name: bind_exporter
    ports:
      - 8053:8053
    networks:
      vpcbr:
        ipv4_address: 172.20.0.14
`

`prometheuscommunity/bind-exporter:v0.3.0                   "/bin/bind_exporter …"   15 minutes ago      Up 15 minutes           9100/tcp 
`
docker logs
`time="2021-04-14T13:22:39Z" level=info msg="Starting bind_exporter (version=0.3.0, branch=HEAD, revision=c34ff3d6b4817f42e74b2b05b3797cf99683b4a9)" source="bind_exporter.go:491"
time="2021-04-14T13:22:39Z" level=info msg="Build context (go=go1.12.14, user=root@48c85d39c9a6, date=20200109-18:54:09)" source="bind_exporter.go:492"
time="2021-04-14T13:22:39Z" level=info msg="Configured to collect statistics \"server,view,tasks\"" source="bind_exporter.go:493"
time="2021-04-14T13:22:39Z" level=info msg="Starting Server: :9119" source="bind_exporter.go:517"
`

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
