### ISSUE TITLE
Insufficient Metrics Information

### ISSUE THREAD

**Issue by leeminseob** [prometheus-community/bind_exporter#110]
Kubernetes 1.21.0
 - Grafana : 7.5.6
 - Prometheus : 2.13.*
Bind : 9.11.4 with libxml2 (2.9.1)
Bind_exporter : 0.4.0

Hello.
I installed bind_exporter like the following website.
https://computingforgeeks.com/how-to-monitor-bind-dns-server-with-prometheus-and-grafana/

However, if you look at the collected metrics, there is a lack of data.
There are only have the following data.
 - bind_exporter_build_info
 - bind_process_cpu_seconds_total
 - bind_process_max_fds
 - bind_process_resident_memory_bytes
 - bind_process_start_time_seconds
 - bind_process_virtual_memory_bytes
 - bind_process_virtual_memory_max_bytes
 - bind_up

I want to collecte metrics about queries.
How can I fix this problems?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
