### ISSUE TITLE
Problem to install over Ubuntu18.0.4

### ISSUE THREAD

**Issue by kmorales026** [prometheus-community/bind_exporter#121]
Hi, I try to intall it and I get this error

root@grafana:~# go get github.com/prometheus-community/bind_exporter
          # golang.org/x/net/http2
go/src/golang.org/x/net/http2/client_conn_pool.go:302:6: undefined: errors.Is
go/src/golang.org/x/net/http2/server.go:240:72: undefined: tls.VersionTLS13
go/src/golang.org/x/net/http2/transport.go:417:30: undefined: errors.Is
go/src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
go/src/golang.org/x/net/http2/transport.go:2059:5: undefined: errors.Is
go/src/golang.org/x/net/http2/transport.go:2063:5: undefined: errors.Is
go/src/golang.org/x/net/http2/transport.go:2067:5: undefined: errors.Is

github.com/prometheus/client_golang/prometheus

go/src/github.com/prometheus/client_golang/prometheus/go_collector.go:353:15: undefined: debug.ReadBuildInfo
root@grafana:~#                               

what is the problem?

Thanks!

**Comment by DoM1niC** [comment]
which **GO** Version 
do you tried ???
```
go get
go build
```
or do 
`make`

**Comment by SuperQ** [comment]
This is a problem because your Go compiler is too old.
