### ISSUE TITLE
Need help please ---- server returned HTTP status 404 No such URL  

### ISSUE THREAD

**Issue by spnabi** [prometheus-community/bind_exporter#128]
I am trying to setup Grafana dashboard with Prometheus/bind_exporter. I have followed the document but not getting anywhere. 
I have bind9 DNS serve running standalone.
I built Grafana server which is also standalone, installed bind_exporter and Prometheus but its not collecting any data. I am getting following errors not sure what I am doing wrong.
One thing I would like to know do i need to install bind_exporter in bind9 DNS server other that that I followed exact steps but when I run prometheus script it failed and getting this error message. 

ts=2022-01-13T17:52:27.520Z caller=web.go:570 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2022-01-13T17:52:27.521Z caller=main.go:755 level=error msg="Unable to start web listener" err="listen tcp 0.0.0.0:9090: bind: address already in use"

Prometheus.yml file:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "bind9-dns"
    static_configs:
      - targets: ["10.10.10.1:8080"]

bind_exporter service file:
[Unit]
Description=Prometheus
Documentation=https://github.com/digitalocean/bind_exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecReload=/bin/kill -HUP $MAINPID
[Unit]
Description=Prometheus
Documentation=https://github.com/digitalocean/bind_exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/bind_exporter \
  --bind.pid-file=/var/opt/isc/isc-bind/named/var/run/named.pid \
  --bind.timeout=20s \
  --web.listen-address=0.0.0.0:9153 \
  --web.telemetry-path=/metrics \
  --bind.stats-url=http://localhost:8053/ \
  --bind.stats-groups=server,view,tasks

SyslogIdentifier=prometheus
Restart=always

[Install]
WantedBy=multi-user.target

prometheus.service file:
[Unit]
Description=Prometheus
Documentation=https://prometheus.io/docs/introduction/overview/
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
Environment="GOMAXPROCS=1"
User=prometheus
Group=prometheus
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=0.0.0.0:9090 \
  --web.external-url=

SyslogIdentifier=prometheus
Restart=always

[Install]
WantedBy=multi-user.target

bind_exporter script:
level=info ts=2022-01-13T17:57:35.604Z caller=bind_exporter.go:542 msg="Starting bind_exporter" version="(version=0.5.0, branch=HEAD, revision=792f7f381f95fbe5fb319b18cedb9ae6f6ad013b)"
level=info ts=2022-01-13T17:57:35.604Z caller=bind_exporter.go:543 msg="Build context" build_context="(go=go1.17.3, user=root@711e62b7164b, date=20211123-09:00:54)"
level=info ts=2022-01-13T17:57:35.604Z caller=bind_exporter.go:544 msg="Collectors enabled" collectors=server,view,tasks
level=info ts=2022-01-13T17:57:35.604Z caller=bind_exporter.go:558 msg="Listening on" address=:9119
level=info ts=2022-01-13T17:57:35.605Z caller=tls_config.go:195 msg="TLS is disabled." http2=false

**Comment by spnabi** [comment]
![image](https://user-images.githubusercontent.com/97692890/149384410-66f4cf71-58a5-432b-8c83-0d3463765471.png)

**Comment by SuperQ** [comment]
You have the wrong port. 8080 -> 9153.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by spnabi** [comment]
Thanks for your reply. I am new in this forum when I clicked the community i don't see any where where i can post my question. Can you please let me know where is that community forum resides. Thanks
