### ISSUE TITLE
Exporter for Bind 9.10.16

### ISSUE THREAD

**Issue by chinhson1998** [prometheus-community/bind_exporter#147]
Hi team,

I monitoring for BIND 9.10.16 but error message msg="Couldn't retrieve BIND stats" err="unexpected status 404 No such URL".
Please let me know exporter 0.505 version has support BIND 9.10.16 or not?
Thanks.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by christian-simmen** [comment]
Just for the records: BIND 9.10 is EOL for some years. 

You should consider updating to some supported version. For more information on BINDs release model: https://www.isc.org/blogs/2021-bind-release-model/
