### ISSUE TITLE
Can't install Ubuntu 20

### ISSUE THREAD

**Issue by kmorales026** [prometheus-community/bind_exporter#148]
Hi, I can't install bind_exporter, I get this error message:

root@grafana:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

root@grafana:~# 
root@grafana:~# go get github.com/prometheus-community/bind_exporter
# github.com/prometheus/common/expfmt
go/src/github.com/prometheus/common/expfmt/decode.go:89:34: cannot use v (type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.ReadDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
go/src/github.com/prometheus/common/expfmt/encode.go:120:36: cannot use v (type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.WriteDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
go/src/github.com/prometheus/common/expfmt/text_create.go:46:27: undefined: io.Discard
# github.com/prometheus/procfs/internal/util
go/src/github.com/prometheus/procfs/internal/util/parse.go:69:15: undefined: os.ReadFile
go/src/github.com/prometheus/procfs/internal/util/parse.go:78:15: undefined: os.ReadFile
go/src/github.com/prometheus/procfs/internal/util/readfile.go:36:9: undefined: io.ReadAll
# golang.org/x/sys/unix
go/src/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
go/src/golang.org/x/sys/unix/syscall_linux.go:2256:9: undefined: unsafe.Slice
go/src/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
go/src/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
# golang.org/x/net/http2
go/src/golang.org/x/net/http2/transport.go:437:45: undefined: os.ErrDeadlineExceeded
root@grafana:~# 

how can I fix it?

**Comment by SuperQ** [comment]
Your Go version is too old.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
