### ISSUE TITLE
Proposal: drop support for XML v2 statistics

### ISSUE THREAD

**Issue by dswarbrick** [prometheus-community/bind_exporter#170]
The XML v2 stats API has been deprecated since [BIND 9.10.0](https://downloads.isc.org/isc/bind9/9.10.0/RELEASE-NOTES-BIND-9.10.0.txt):

> The version 3 XML schema for the statistics channel, including new statistics and a flattened XML tree for faster parsing, is no longer optional. The version 2 XML schema is now deprecated.

Additionally, BIND 9.9.x was [EOL](https://kb.isc.org/docs/bind-9-end-of-life-dates)'d in July 2018.

I propose that we drop support for XML v2 stats, which would simplify some long overdue cleanup of the core of bind_exporter, and decoupling some of the overly tightly coupled XML code.

@SuperQ WDYT?

**Comment by SuperQ** [comment]
Seems reasonable to me.
