### ISSUE TITLE
Exporter unable to query bind `unexpected status 404 No such URL`

### ISSUE THREAD

**Issue by onedr0p** [prometheus-community/bind_exporter#172]
Bind9 Image: `docker.io/internetsystemsconsortium/bind9:9.19`

I have confirmed I can open the dashboard at this address http://192.168.254.2:8080

```
✖ docker run --rm -p 9119:9119 prometheuscommunity/bind-exporter:v0.6.1 --bind.stats-url http://192.168.254.2:8080
level=info ts=2023-05-02T19:21:41.413Z caller=bind_exporter.go:541 msg="Starting bind_exporter" version="(version=0.6.1, branch=HEAD, revision=fe2ec1a73e6b22957e36f75a51b6693e7bdf9a56)"
level=info ts=2023-05-02T19:21:41.413Z caller=bind_exporter.go:542 msg="Build context" build_context="(go=go1.20.2, platform=linux/arm64, user=root@9896e631ebec, date=20230322-10:22:40, tags=netgo static_build)"
level=info ts=2023-05-02T19:21:41.413Z caller=bind_exporter.go:543 msg="Collectors enabled" collectors=server,view,tasks
level=info ts=2023-05-02T19:21:41.413Z caller=tls_config.go:232 msg="Listening on" address=[::]:9119
level=info ts=2023-05-02T19:21:41.413Z caller=tls_config.go:235 msg="TLS is disabled." http2=false address=[::]:9119
level=error ts=2023-05-02T19:21:47.950Z caller=bind_exporter.go:441 msg="Couldn't retrieve BIND stats" err="unexpected status 404 No such URL"
level=error ts=2023-05-02T19:21:50.629Z caller=bind_exporter.go:441 msg="Couldn't retrieve BIND stats" err="unexpected status 404 No such URL"
level=error ts=2023-05-02T19:28:06.329Z caller=bind_exporter.go:441 msg="Couldn't retrieve BIND stats" err="unexpected status 404 No such URL"
```

The metrics endpoint only show the go runtime stats.

**Comment by capbsh** [comment]
Did you find a solution to the problem?

**Comment by christian-simmen** [comment]
Hi guys,

same here: as far as I know, BIND 9.19 is a development branch (https://www.isc.org/blogs/2021-bind-release-model/).
I would strongly recommend staying with BIND 9.18 for now.

Best regards, 
Christian

**Comment by dswarbrick** [comment]
BIND 9.19-dev does not appear to expose a `/xml/v3/tasks` or `/json/v1/tasks` endpoint, which are requested by bind_exporter.

**Comment by dswarbrick** [comment]
Alternatively, you can run bind_exporter without tasks metrics by using the flag `--bind.stats-groups=server,view`.

@SuperQ Since BIND 9.19 has now trickled down to Debian testing, and is likely to appear in other distros (e.g. Ubuntu 24.04 LTS next year), how do you think we should tackle this? Adjust the flag default, or keep the status quo but make the 404 error non-fatal?
