### ISSUE TITLE
make: *** [Makefile.common:171: common-lint] Error 2

### ISSUE THREAD

**Issue by jocaplanaltonet** [prometheus-community/bind_exporter#174]
Compiling from source;
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyzeRecursive.func1
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:42 +0xae
Descarregando processo filho 0x55ef4f506590 PID 15838
make: *** [Makefile.common:171: common-lint] Error 2
Removendo o processo filho 0x55ef4f506590 PID 15838 da cadeia.

**Comment by SuperQ** [comment]
Sounds like you may have an incompatible version of golangci-lint installed. Or you have not enough resources to run the linter locally.
