### ISSUE TITLE
Use json instead of xml

### ISSUE THREAD

**Issue by capbsh** [prometheus-community/bind_exporter#177]
Hi guys :)
When we can use JSON instead of XML? On which release?
I can't make newer releases and face some problems when making themes.

I want to use the default XML in Ubuntu 22.04 and BIND 9.19 but I get the error 

> caller=bind_exporter.go:441 msg="Couldn't retrieve BIND stats" err=" unexpected status 404 No such URL" 

can anyone help me?

**Comment by christian-simmen** [comment]
Hi capbsh,

as far as I know BIND 9.19 is a development branch (https://www.isc.org/blogs/2021-bind-release-model/).
I would strongly recommend staying with BIND 9.18 for now.

Best, 
Christian

**Comment by capbsh** [comment]
Tnx bro
I had this version and I encountered a problem, so I wanted to test another version.

**Comment by SuperQ** [comment]
The json format should work in master, I think we just need to cut a new relesae.

**Comment by SuperQ** [comment]
https://github.com/prometheus-community/bind_exporter/pull/180

**Comment by capbsh** [comment]
Special thanks for the speed of action 👍  @SuperQ 
But unfortunately, my problem still exists in both versions. (Bind 9.18, Bind 9.19).
There is no problem when I control the address only ( curl http://localhost:8053/json ). But as soon as the attached command is executed, I encounter the displayed error. I have this error after trying all types of XML, auto, and JSON in both versions. ( bind_exporter 6, bind_exporter 7 ) .


![Screenshot 2023-08-12 195701](https://github.com/prometheus-community/bind_exporter/assets/88495703/e9d0d429-2e54-496a-a50d-e3d078451a39)
