### ISSUE TITLE
How do I send data to my remote Prometheus server?

### ISSUE THREAD

**Issue by Blason** [prometheus-community/bind_exporter#181]
Hi Team,

I started my docker successfully however wondering if my prometheus and grafana server is listening on 192.168.5.78 how do I dispatch the data to remote server?

TIA
Blason R

**Comment by capbsh** [comment]
Hi Blason
You have two ways to do this:
First, instead of using the local IP address, bind to 0.0.0.0.
Second, using nginx as a reverse proxy

** Do not forget the firewall settings in both methods.
