### ISSUE TITLE
EOF error with the bind exporter 0.7.0.linux-amd64 and 0.6.1.linux-amd64

### ISSUE THREAD

**Issue by ghost** [prometheus-community/bind_exporter#185]
I have configured the bind exporter and it is getting the data from the named service. The URL is **curl -k http://127.0.0.1:8080** as my named is running on the 8080 port. This URL output is in the JSON format. I'm getting the below error with the bind exporter service. What should I do to overcome the below issue? Please give me a suggestion as soon as possible.

 **prometheus[2087]: level=error ts=2023-09-06T03:26:06.789Z caller=bind_exporter.go:441 msg="Couldn't retrieve BIND stats" err="failed to unmarshal XML response: EOF"**

**Comment by dswarbrick** [comment]
Please provide the full set of command line flags with which you are executing bind_exporter and specify what version of BIND you are using.

A curl request against the BIND stats HTTP endpoint should return XML by default, unless you explicitly request e.g. `http://localhost:8080/json`.

snmp_exporter only supports parsing BIND JSON stats from v0.7.0 onward (and even then it must be explicitly enabled with the `--bind.stats-version=json` flag).

**Comment by dswarbrick** [comment]
@SuperQ OP is now a ghost user. Please close this.
