### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by grobie** [prometheus-community/bind_exporter#19]
We've been the current master in production for a while and it's pretty stable. Can we get a proper release including tarballs for each arch/os? I'm happy to take this over if you need help if you add me as collaborator to this repository.

**Comment by cagedmantis** [comment]
It's definitely time for a new release. I will reach out via irc to talk about the canonical release process.

**Comment by anarcat** [comment]
*ping* it seems that 0.2.0 was somehow released, but that has been a while already, and new commits have accumulated since then... it would be great to have an updated version again!

**Comment by anarcat** [comment]
ping again! there hasn't been a release over a year and while the number of commits is low, there are some important fixes in there including #50 and others. it would be great to have a (say) 0.3.0 release instead of the current `-dev` release...

**Comment by SuperQ** [comment]
Closing in favor of #55 (0.3.0)
