### ISSUE TITLE
bind_Exporter not able to fetch bind stats

### ISSUE THREAD

**Issue by HesaMtiPu** [prometheus-community/bind_exporter#190]
after Compile of bind_exporter this error is showing
+++++++++++++++++++++++++++++++++++++++
caller=bind_exporter.go:449 level=error msg="Couldn't retrieve BIND stats" err="unexpected status for \"http://localhost:8053/json/v1/server\": 404 No such URL
++++++++++
bind Version:-BIND 9.18.16

**Comment by dswarbrick** [comment]
This may indicate that your BIND has not been compiled with JSON support, although that is unlikely if you are using a packaged version of BIND from your distro.

Are you able to fetch the base URL with curl? e.g. `curl http://localhost:8053/json/v1`

Can you elaborate on your environment? e.g. include output of `uname -a`

Also the output of `named -V` will show detailed information about how your BIND was compiled.

**Comment by dswarbrick** [comment]
There also appears to be a trailing backslash in the URL that your bind_exporter has requested. I'm not sure if this is merely a copy and paste error in your log output from when you opened the issue, or whether you really have configured your bind_exporter to probe `http://localhost:8053/json/v1/server\`.

If the latter, then this obviously won't work.

**Comment by HesaMtiPu** [comment]
Thank you @dswarbrick  
problem resolved.
