### ISSUE TITLE
containerized HOWTO?

### ISSUE THREAD

**Issue by ahammond** [prometheus-community/bind_exporter#20]
We run named in a container. I'd like to run bind_exporter in a container, too. However it looks like bind_exporter wants to run inside the same container as named? Is this correct? Is this required? Is there a HOWTO for configuring bind_exporter to run in a container beside the bind container?

**Comment by a-nldisr** [comment]
As far as i know there is no HOWTO, but i would expect that you only need the container with the bind_exporter binary to be able to connect to the port where you export the libxml2 data from named.

**Comment by Cougar** [comment]
Just for a reference, I run it in separate container but using the same network namespace (to use 127.0.0.1) and it works fine.

**Comment by SuperQ** [comment]
This seems resolved.
