### ISSUE TITLE
Provide docker-image on docker hub?

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus-community/bind_exporter#22]
It would be awesome if you could provide a pre-baked docker image on docker hub!

**Comment by dannyk81** [comment]
+1

**Comment by thehar** [comment]
+1

**Comment by jacob-go** [comment]
+1

**Comment by flouthoc** [comment]
+1

**Comment by SuperQ** [comment]
We finally have Docker images published. Please give them a try.

https://hub.docker.com/repository/docker/prometheuscommunity/bind-exporter
