### ISSUE TITLE
Make fails on Centos7

### ISSUE THREAD

**Issue by rajkumar-agaram** [prometheus-community/bind_exporter#28]
Tried setting up bind_exporter on Centos7 with Go version 1.83. Make fails with below error

bind_exporter-master]# make all
>> formatting code
# runtime
../runtime/signal_unix.go:27: _SIG_DFL redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:15
../runtime/signal_unix.go:28: _SIG_IGN redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:16
../runtime/signal_unix.go:37: fwdSig redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:25
../runtime/signal_unix.go:42: disableSigChan redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:35
../runtime/signal_unix.go:43: enableSigChan redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:36
../runtime/signal_unix.go:44: maskUpdatedChan redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:37
../runtime/signal_unix.go:56: signalsOK redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:49
../runtime/signal_unix.go:62: initsig redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:55
../runtime/signal_unix.go:97: sigInstallGoHandler redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:90
../runtime/signal_unix.go:122: sigenable redeclared in this block
	previous declaration at ../runtime/signal1_unix.go:115
../runtime/signal_unix.go:122: too many errors
make: *** [promu] Error 2

**Comment by roman8422** [comment]
In case someone else would come here searching for the answer like I did, here's the easiest way to do it:
```
docker container run \
                 -v $(pwd):/root/temp \
                 -e GOPATH=/root/go \
                 --rm centos:7 /bin/sh \
                 -c 'yum install -y epel-release \
                  && yum install -y golang \
                  && yum -y groupinstall "Development Tools" \
                  && go get github.com/digitalocean/bind_exporter \
                  && cd $GOPATH/src/github.com/digitalocean/bind_exporter \
                  && make \
                  && mv bind_exporter /root/temp/'
```

**Comment by roman8422** [comment]
In case someone else would come here searching for the answer like I did, here's the easiest way to do it:
```
docker container run \
                 -v $(pwd):/root/temp \
                 -e GOPATH=/root/go \
                 --rm centos:7 \
                 /bin/sh -c \
                    'yum install -y epel-release \
                  && yum install -y golang \
                  && yum -y groupinstall "Development Tools" \
                  && go get github.com/digitalocean/bind_exporter \
                  && cd $GOPATH/src/github.com/digitalocean/bind_exporter \
                  && make \
                  && mv bind_exporter /root/temp/'
```

**Comment by SuperQ** [comment]
This should be fixed by the latest build updates.
