### ISSUE TITLE
Provide an alpine package of executable

### ISSUE THREAD

**Issue by thehar** [prometheus-community/bind_exporter#29]

**Comment by Horbi** [comment]
0x07aa9c7e03a795d250a2ac48bd73b9c7f8adab69a549cebd97fc157a093a5a4a

**Comment by SuperQ** [comment]
We've switched to publishing via Prometheus upstream promu packaging. For distribution packages, we should move this to the upstream issue.

https://github.com/prometheus/promu/issues/93
