### ISSUE TITLE
project alive. Need to use and help in setting up.

### ISSUE THREAD

**Issue by ansham22** [prometheus-community/bind_exporter#30]
I am having issues while setting up this project can someone please help me with the same and reply me if this project is alive so that I can post logs of my problem and get this up.

**Comment by grobie** [comment]
Yes, the project is alive and in production use at several companies.

**Comment by ansham22** [comment]
I have set it up in my production. Need proper documentation on this so that I can setup grafana dashboards. Can you please point me to the same @grobie

**Comment by ansham22** [comment]
How can I view metrics explanation of the same @grobie

**Comment by grobie** [comment]
The only documentation available are the help strings of the metrics. Go to `/metrics` of the bind exporter to see them. Besides that, please refer to the bind statistics documentation itself.

**Comment by ansham22** [comment]
@grobie where can I find bind statistics documentation. Actually I am stuck in an issue where sometimes my bind dns server responds slowly to queries.

**Comment by grobie** [comment]
There is no good documentation. I googled a lot, read the source code of bind and looked at the stats pages.

**Comment by Amittiwarishivkant** [comment]
Can anyone help me how to implement SMS API any which have low cost

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
