### ISSUE TITLE
make compiling error in bind exporter

### ISSUE THREAD

**Issue by nithyashreesundar** [prometheus-community/bind_exporter#34]
I have a issue while configuring bind exporter in centos.
Please give the solution 

 make
>> formatting code
can't load package: package _/prometheus/source/bind_exporter-master: cannot find package "_/prometheus/source/bind_exporter-master" in any of:
	/usr/local/go/src/_/prometheus/source/bind_exporter-master (from $GOROOT)
	/prometheus/go/src/_/prometheus/source/bind_exporter-master (from $GOPATH)
can't load package: package _/prometheus/source/bind_exporter-master/bind: cannot find package "_/prometheus/source/bind_exporter-master/bind" in any of:
	/usr/local/go/src/_/prometheus/source/bind_exporter-master/bind (from $GOROOT)
	/prometheus/go/src/_/prometheus/source/bind_exporter-master/bind (from $GOPATH)
can't load package: package _/prometheus/source/bind_exporter-master/bind/auto: cannot find package "_/prometheus/source/bind_exporter-master/bind/auto" in any of:
	/usr/local/go/src/_/prometheus/source/bind_exporter-master/bind/auto (from $GOROOT)
	/prometheus/go/src/_/prometheus/source/bind_exporter-master/bind/auto (from $GOPATH)
can't load package: package _/prometheus/source/bind_exporter-master/bind/v2: cannot find package "_/prometheus/source/bind_exporter-master/bind/v2" in any of:
	/usr/local/go/src/_/prometheus/source/bind_exporter-master/bind/v2 (from $GOROOT)
	/prometheus/go/src/_/prometheus/source/bind_exporter-master/bind/v2 (from $GOPATH)
can't load package: package _/prometheus/source/bind_exporter-master/bind/v3: cannot find package "_/prometheus/source/bind_exporter-master/bind/v3" in any of:
	/usr/local/go/src/_/prometheus/source/bind_exporter-master/bind/v3 (from $GOROOT)
	/prometheus/go/src/_/prometheus/source/bind_exporter-master/bind/v3 (from $GOPATH)
make: *** [format] Error 1

**Comment by grobie** [comment]
Please make yourself familiar with Golang and its file structures. There are many blog posts on that topic.

In summary: make sure `$GOPATH` is set and clone this repository to `$GOPATH/src/github.com/digitalocean/bind_exporter`.

**Comment by SuperQ** [comment]
This should be fixed by the latest build updates.
