### ISSUE TITLE
Release v0.2.0 Doesn't Execute on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [prometheus-community/bind_exporter#38]
Hi, really having a tough time with golang and I can't get make to work at all (as noted in similar issue threads) so instead of compiling I was hoping to just use the pre-compiled binary for v0.2.0 

Release downloaded from: 
https://github.com/digitalocean/bind_exporter/releases/download/v0.2.0-dev/bind_exporter

**Works perfectly fine on my Mac:**
```
Macbook$ ./bind_exporter
INFO[0000] Starting bind_exporter (version=0.2.0-dev, branch=master, revision=dae68f9a72da14e080aea554b7d4f1495904ba1a)  source="bind_exporter.go:455"
INFO[0000] Build context (go=go1.8.3, user=root@a8276f7e0479, date=20
```

**Won't run at all on Ubuntu 16:** 
```
Linux_Server$ ./bind_exporter
-bash: ./bind_exporter: cannot execute binary file: Exec format error
```

The compilation from source issues I'm experiencing are the same `type` error noted here from another user: https://github.com/digitalocean/bind_exporter/issues/32

I'll continue to hack away at it but any help is very much appreciated.

**Comment by SuperQ** [comment]
Fixed binaries will be published by the next release.
