### ISSUE TITLE
Make fails on linux/armv7l

### ISSUE THREAD

**Issue by tdefise** [prometheus-community/bind_exporter#44]
root@daac0d6bb19f:~/go/src/bind_exporter-master# make
>> formatting code
cmd/go: unsupported GOOS/GOARCH pair linux/armv7l
Makefile:55: recipe for target 'promu' failed
make: *** [promu] Error 2

**Comment by SuperQ** [comment]
This should be fixed with the latest build updates. Please re-open if it's still a problem.
