### ISSUE TITLE
bind_config_time_seconds not exported. Removed from Bind or mapped to another ID?

### ISSUE THREAD

**Issue by ptselios-inmarsat** [prometheus-community/bind_exporter#45]
My environment: 
CentOS 7.5 (Bind & Prometheus/Grafana)
Bind 9.9.4
Bind Exporter: 0.2.0_dev

Problem: I cannot find the under subject metric. I don't know if it's mapped in another variable, but I cannot find it in the metrics.

**Comment by atriumcarceri** [comment]
same, bind 9.8, debian 7, exporter version 0.2.0-dev

**Comment by dswarbrick** [comment]
Works as expected with BIND 9.11 on debian buster:
```
# HELP bind_config_time_seconds Time of the last reconfiguration since unix epoch in seconds.
# TYPE bind_config_time_seconds gauge
bind_config_time_seconds 1.601287894e+09
```
Note that the metric will only be exposed if your have issued a config reload of BIND since starting it.
```go
    if !c.stats.Server.ConfigTime.IsZero() {
        ch <- prometheus.MustNewConstMetric(
            configTime, prometheus.GaugeValue, float64(c.stats.Server.ConfigTime.Unix()),
        )   
    }
```

**Comment by SuperQ** [comment]
This seems solved.
