### ISSUE TITLE
improve documentation: what are the units in?

### ISSUE THREAD

**Issue by benapetr** [prometheus-community/bind_exporter#53]
The graphs in grafana https://grafana.com/grafana/dashboards/1666 are cool, but there is absolutely no mention anywhere in documentation or graphs themselves, what are the units?

I can see for example incoming queries - what are they:

* Queries since launch?
* Queries per second?
* Queries per minute?
* Queries since last fetch?

It would be really useful to know this, seeing just numbers with no context is misleading and useless

**Comment by SuperQ** [comment]
Weird, it looks like all the queries in that dashboard are `increase(metric[120s])`, which is queries per 2 minutes.

Since this dashboard isn't maintained here, there's not much we can do to fix it.
