### ISSUE TITLE
Can't run behind nginx proxy 502 Bad Gateway

### ISSUE THREAD

**Issue by rebjan** [prometheus-community/bind_exporter#54]
Hello Guys, 

Thank you for your BIND-DNS Exporter

I am trying to run exporter behind Nginx proxy (via SSL secure communication)

```
[root@ns1 ~]# curl https://ns1.domain.tld
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>

[root@ns1 ~]# curl localhost:9119
<html>
<head><title>Bind Exporter</title></head>
<body>
<h1>Bind Exporter</h1>
<p><a href='/metrics'>Metrics</a></p>
</body>
 </html>
```

`cmdline: /usr/bin/bind_exporter -bind.pid-file /var/run/named/named.pid -bind.stats-groups server,view,tasks`

Please find my config file below, How can I fix this, 

```
server {
    listen 80;
    server_name ns1.domain.tld localhost;
    return 301 https://ns1.domain.tld$request_uri;
}    

server {
    listen 443 ssl;
    server_name ns1.domain.tld loclahost;
    
    client_max_body_size 40M;
    charset utf-8;

    location / {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
    	proxy_pass  http://127.0.0.1:9119;
    }
}


    ## Nginx Includes
    # SSL Params
    ssl_stapling on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 5m;

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK';

    ssl_certificate /etc/ssl/dns/fullchain.pem;
    ssl_certificate_key /etc/ssl/dns/privkey.pem;
    #ssl_dhparam /etc/ssl/dtcm-ssl/dhparam.pem;


}
```

**Comment by rebjan** [comment]
> Hello Guys,
> 
> Thank you for your BIND-DNS Exporter
> 
> I am trying to run exporter behind Nginx proxy (via SSL secure communication)
> 
> ```
> [root@ns1 ~]# curl https://ns1.domain.tld
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body>
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.16.1</center>
> </body>
> </html>
> 
> [root@ns1 ~]# curl localhost:9119
> <html>
> <head><title>Bind Exporter</title></head>
> <body>
> <h1>Bind Exporter</h1>
> <p><a href='/metrics'>Metrics</a></p>
> </body>
>  </html>
> ```
> 
> `cmdline: /usr/bin/bind_exporter -bind.pid-file /var/run/named/named.pid -bind.stats-groups server,view,tasks`
> 
> Please find my config file below, How can I fix this,
> 
> ```
> server {
>     listen 80;
>     server_name ns1.domain.tld localhost;
>     return 301 https://ns1.domain.tld$request_uri;
> }    
> 
> server {
>     listen 443 ssl;
>     server_name ns1.domain.tld loclahost;
>     
>     client_max_body_size 40M;
>     charset utf-8;
> 
>     location / {
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection 'upgrade';
>             proxy_set_header Host $host;
>             proxy_cache_bypass $http_upgrade;
>     	proxy_pass  http://127.0.0.1:9119;
>     }
> }
> 
> 
>     ## Nginx Includes
>     # SSL Params
>     ssl_stapling on;
>     ssl_session_cache shared:SSL:10m;
>     ssl_session_timeout 5m;
> 
>     ssl_prefer_server_ciphers on;
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK';
> 
>     ssl_certificate /etc/ssl/dns/fullchain.pem;
>     ssl_certificate_key /etc/ssl/dns/privkey.pem;
>     #ssl_dhparam /etc/ssl/dtcm-ssl/dhparam.pem;
> 
> 
> }
> ```

**Comment by SuperQ** [comment]
This seems like a problem with nginx, not a problem with the exporter.

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mohamedalaa13** [comment]
Hello Rebjan,
Did you manage to solve this issue? and if so, can you please share it with me?
I'm facing same error.
Thanks in advance
