### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by alexjfisher** [prometheus-community/bind_exporter#55]
Hi!

Would it be possible to have a new release including a Linux amd64 binary build?
This would really help us out over at VoxPupuli.  See https://github.com/voxpupuli/puppet-prometheus/pull/312#issuecomment-559181572

Thanks,
Alex

**Comment by anarcat** [comment]
see also #19... i'm afraid this exporter is more or less abandonware at this point :(

**Comment by cagedmantis** [comment]
@anarcat I don't believe bind_exporter is currently being supported. I can create a PR to note that in the documentation. If you know of an organization that is willing to take over support, they may be open to it.

**Comment by alexjfisher** [comment]
[Vox Pupuli](https://voxpupuli.org/) is a good home for abandoned puppet modules, but probably not a great fit for prometheus exporters.  Is there any parallel in the prometheus ecosystem?
@cagedmantis Have you considered maintaining a fork yourself? (noting your previous contributions to this project).  Or maybe the original authors/maintainers would consider given you greater permissions on this repo???

**Comment by anarcat** [comment]
apparenty, the @prometheus-community organization is built for that and this very exporter was discussed recently on their mailing list. so there is hope!

**Comment by SuperQ** [comment]
Yes, feel free to open an issue on https://github.com/prometheus-community/community/issues, if DO agrees, we can find a Prometheus Team member to sponsor the move.

**Comment by anarcat** [comment]
alright, I opened https://github.com/prometheus-community/community/issues/15 to ask the prometheus community to adopt this module.

@digitalocean - would you be okay with @prometheus-community taking over support of this module?

thanks everyone!

**Comment by cagedmantis** [comment]
@andrewsomething Is this something you can help with?

**Comment by rayram23** [comment]
Hey folks, I worked closely with @cagedmantis while at DO. I can help get this moved over to the prometheus community. Give me some time and ill help get it worked out. Thanks for your patience. ;)

**Comment by rayram23** [comment]
Ok, we're good to move this over to the prometheus community. Will message the issue there and as soon as i get an `ack` from them will move the repo.

**Comment by rayram23** [comment]
Moved to prometheus-community!!

**Comment by SuperQ** [comment]
First step in getting a new release done is to update the build.

https://github.com/prometheus-community/bind_exporter/pull/57

**Comment by SuperQ** [comment]
After a little bit of fiddling with the publishing pipeline, we're good to go:

https://github.com/prometheus-community/bind_exporter/releases/tag/v0.3.0
