### ISSUE TITLE
Zero values for some metrics

### ISSUE THREAD

**Issue by timureh** [prometheus-community/bind_exporter#68]
The server has been monitored for a week but according to some charts unchanged...
I attach screenshots.
How can I check that metrics work?

bind_exporter, version 0.3.0 (branch: HEAD, revision: c34ff3d6b4817f42e74b2b05b3797cf99683b4a9)
  build user:       root@48c85d39c9a6
  build date:       20200109-18:54:09
  go version:       go1.12.14

bind9 server version 9.11.5

prometheus server version 0.16.2

Grafana v6.4.3
dashboard https://grafana.com/grafana/dashboards/1666

![Выделение_013](https://user-images.githubusercontent.com/51699692/74717341-0c935700-5252-11ea-882d-ec81420588c2.png)
![Выделение_012](https://user-images.githubusercontent.com/51699692/74717345-0d2bed80-5252-11ea-9ba5-813562fcc5aa.png)
![Выделение_011](https://user-images.githubusercontent.com/51699692/74717349-0dc48400-5252-11ea-99a4-336cc5ecb85d.png)

**Comment by leeminseob** [comment]
Did you fixed it?
