### ISSUE TITLE
SELinux enablement doc update

### ISSUE THREAD

**Issue by sghosh151** [prometheus-community/bind_exporter#71]
When using a custom port for the statistics channel on an SELinux enabled host, the port needs to be tagged with SELinux policy.

https://bugzilla.redhat.com/show_bug.cgi?id=1778349

add custom port to dns_port_t type, which would allow bind to listen on that port. 

$ (sudo) semanage port -a -t dns_port_t -p tcp 8053

All current port assigned to a type could be obtained by command

$ semanage port -l | grep dns_port_t

**Comment by SuperQ** [comment]
This seems a bit too much of an site-specifc implementation detail. I don't think we need to include it here.

As-is, this issue should be enough for people to find via web searching.
