### ISSUE TITLE
Metric with list of views only

### ISSUE THREAD

**Issue by rfrail3** [prometheus-community/bind_exporter#73]
Hello,

It would be nice to have a metric with only the views available on the Bind server. That can allow a less tricky variable settings. Maybe something like:

bind_view_up{view="_bind"} 1
bind_view_up{view="_default"} 1

Thanks,

**Comment by SuperQ** [comment]
Can you explain a little more about how this would work? What problem it solves? Where does the data come from?

**Comment by rfrail3** [comment]
Hello SuperQ:

It would be helpful to get a list with the views configured on the server.

As example, on Grafana, it allow to clearly define a variable with it, for example:
label_values(bind_view_up, view)
instead of something like this workaround:
label_values(bind_resolver_query_errors_total, view)

The data come from the configured zones available.

Does is it hard to implement?

**Comment by SuperQ** [comment]
I don't see `label_values(bind_resolver_query_errors_total, view)` as a workaround, this is a standard Prometheus/Grafana practice. If the existing metrics provide the required information, adding additional metrics is duplication of existing data. This is something we try and avoid.
