### ISSUE TITLE
Make failing on Raspbian 10 (buster) ARMv7 rev 3 (v7l) Pi4B

### ISSUE THREAD

**Issue by mkopnsrc** [prometheus-community/bind_exporter#80]
I'm running into an issue during the command Make. Please see last line for error that I'm getting. I've also attached two colored screenshots showing command Make in run. Any suggestions how do I go about fixing? Thank you guys.

**:~/go/src #** cd $GOPATH/src/github.com/prometheus-community/bind_exporter
**:~/go/src/github.com/prometheus-community/bind_exporter #** make
>> checking code style
>> checking license header
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
diff --git a/go.mod b/go.mod
index 05907bf..91d8497 100644
--- a/go.mod
+++ b/go.mod
@@ -5,6 +5,8 @@ go 1.13
 require (
        github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d // indirect
        github.com/golang/protobuf v1.4.2 // indirect
        github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
        github.com/modern-go/reflect2 v1.0.1 // indirect
        github.com/prometheus/client_golang v1.6.0
        github.com/prometheus/common v0.10.0
        github.com/sirupsen/logrus v1.6.0 // indirect
diff --git a/vendor/modules.txt b/vendor/modules.txt
index f60df2f..f060de9 100644
--- a/vendor/modules.txt
+++ b/vendor/modules.txt
..............
..............
..............
 gopkg.in/alecthomas/kingpin.v2 v2.2.6
 gopkg.in/alecthomas/kingpin.v2
 make: *** [Makefile.common:216: common-unused] Error 1

![image](https://user-images.githubusercontent.com/2036998/86132492-f2496f80-bab4-11ea-926b-17cfceb6b46f.png)
![image](https://user-images.githubusercontent.com/2036998/86132514-fbd2d780-bab4-11ea-8f5f-ce8f0a1df1e1.png)

**Comment by SuperQ** [comment]
What version of Go is this?
