### ISSUE TITLE
Add support for JSON statistics-channels

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/bind_exporter#82]
Bind now supports stats over JSON.

**Comment by dswarbrick** [comment]
I'm already fairly familiar with the JSON stats in BIND, as I implemented support for it in Telegraf's BIND plugin. However, looking at the code of bind_exporter, I see that there are a few places where it is somewhat tightly coupled to XML unmarshalling, which would require a bit of refactoring to allow the addition of JSON support without too much duplicated code.

**Comment by albsga** [comment]
Hi I see that ISC has an implementation using json:

https://github.com/isc-projects/stork/blob/master/backend/agent/prombind9exporter.go
