### ISSUE TITLE
Proposal: remove vendor directory

### ISSUE THREAD

**Issue by dswarbrick** [prometheus-community/bind_exporter#86]
In line with node_exporter recently removing the vendor directory, it would simplify packaging if bind_exporter merely used go.mod and modern dependency management.

It looks like a few other things could do with a bit of modernizing too (like the removal of `GO111MODULE=on`)

What do you think, @SuperQ ?

**Comment by SuperQ** [comment]
I'm working on bringing the removed-vendor-dir to the main Prometheus repo. I think we're going to have a discussion about it in the next developer meeting. Then I think we'll start bringing the changes to all of the repos.

**Comment by dswarbrick** [comment]
Closed by #92.
